### ISSUE TITLE
 npm run setup --silent: digital envelope routines::unsupported

### ISSUE THREAD

**Issue by libelle2000** [kentcdodds/react-fundamentals#233]
When I run

I am getting an error.

```
rewe@rewes-MBP: ~/Documents/Docu/kam/epicreact/react-fundamentals main
 $ git --version                                                                                                                                                  [12:05:11]
git version 2.30.1 (Apple Git-130)

rewe@rewes-MBP: ~/Documents/Docu/kam/epicreact/react-fundamentals main
 $ npm --version                                                                                                                                                  [12:06:53]
8.1.2

rewe@rewes-MBP: ~/Documents/Docu/kam/epicreact/react-fundamentals main
 $ node --version                                                                                                                                                 [12:06:56]
v17.1.0

rewe@rewes-MBP: ~/Documents/Docu/kam/epicreact/react-fundamentals main
 $ npm run setup --silent                                                                                                                                         [12:07:01]
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
    ✅  Success: System Validation


    ▶️  Starting: Dependency Installation
          Installing third party code dependencies so the workshop works properly on this computer.
          Running the following command: npm install --legacy-peer-deps --no-save
    ✅  Success: Dependency Installation


    ▶️  Starting: Project Validation
          Running validation checks to ensure dependencies were installed properly
          Running the following command: npm run validate -s

 RUNS  src/__tests__/05.js
 RUNS  src/__tests__/05.js
 RUNS  src/__tests__/06.extra-2.js
 RUNS  src/__tests__/07.js
 RUNS  src/__tests__/06.extra-3.js
 RUNS  src/__tests__/06.js

Test Suites: 0 of 5 total
Tests:       0 total
Snapshots:   0 total
Time:        3 sError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/rewe/Documents/Docu/kam/epicreact/react-fundamentals/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
    🚨  Failure: Project Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.
FAIL

rewe@rewes-MBP: ~/Documents/Docu/kam/epicreact/react-fundamentals main
 $
```

**Comment by kentcdodds** [comment]
Hi @libelle2000,

I'm afraid I've never seen anything like this before 😬 I'm not sure what this could be. I'm guessing Node v17 doesn't work very well. Could you downgrade to Node v16?

**Comment by libelle2000** [comment]
Hi @kentcdodds,

That fixed my issue. 

Thank you!

In detail I did:

```
$ nvm install 16.13.0
$ node --version
$ npm start
```


FYI: 
In https://epicreact.dev/modules/react-fundamentals/react-fundamentals-welcome you say
> It will ask you for your email. 

This didn't pop up for me. Anyway, thank you!
