### ISSUE TITLE
Stopped dead in my tracks before I can even begin.

### ISSUE THREAD

**Issue by w3casey** [kentcdodds/react-fundamentals#235]
I am having issues getting the project setup and running. I have followed the instructions exactly. I am not using a proxty or a vpn, and I am on a m1 macbook air. After the initial setup failing I did npm run and npm validate and this happened.

cgw@Caseys-MacBook-Air react-fundamentals % npm run validate

> @kentcdodds/react-fundamentals@1.0.0 validate
> npm-run-all --parallel build test:coverage lint

> @kentcdodds/react-fundamentals@1.0.0 build
> react-scripts build

> @kentcdodds/react-fundamentals@1.0.0 lint
> eslint .

> @kentcdodds/react-fundamentals@1.0.0 test:coverage
> npm run test -- --watchAll=false

> @kentcdodds/react-fundamentals@1.0.0 test
> react-scripts test --env=jsdom "--watchAll=false"

 RUNS  src/__tests__/05.js
 RUNS  src/__tests__/06.extra-2.js
 RUNS  src/__tests__/07.js
 RUNS  src/__tests__/06.extra-3.js
 RUNS  src/__tests__/06.js

Test Suites: 0 of 5 total
Tests:       0 total
Snapshots:   0 total
Time:        0 sCreating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/cgw/Documents/Development/web/epicReact/react-fundamentals/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
ERROR: "build" exited with 1.

what am I meant to do?

**Comment by kentcdodds** [comment]
Hi @w3casey,

To fix this, downgrade from node 17 (which is an experimental version of node) to node 16.

**Comment by w3casey** [comment]
Will try this when I wake up, thanks.On Dec 6, 2021 8:42 PM, "Kent C. Dodds" ***@***.***> wrote:
Hi @w3casey,
To fix this, downgrade from node 17 (which is an experimental version of node) to node 16.

**Comment by w3casey** [comment]
> Hi @w3casey,
> 
> To fix this, downgrade from node 17 (which is an experimental version of node) to node 16.

Downgrading to node 16 resolved the problem, thanks.

**Comment by kentcdodds** [comment]
I've updated the validation script to not allow node 17. Thanks for reporting!
