### ISSUE TITLE
Validation failure once setup complete

### ISSUE THREAD

**Issue by JCorrivo** [kentcdodds/react-fundamentals#252]
git version 2.34.1.windows.1
node v16.14.0
npm 8.5.0

```
 RUNS  src/__tests__/05.js
 RUNS  src/__tests__/06.extra-2.js
 RUNS  src/__tests__/07.js
 RUNS  src/__tests__/06.extra-3.js
 RUNS  src/__tests__/06.js

Test Suites: 0 of 5 total
Tests:       0 total
Snapshots:   0 total
Time:        1 snode:internal/modules/cjs/loader:361
      throw err;
      ^

Error: Cannot find module 'C:\coding\react-fundamentals\node_modules\postcss-loader\src\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getStyleLoaders (C:\coding\react-fundamentals\node_modules\react-scripts\config\webpack.config.js:129:25)
    at module.exports (C:\coding\react-fundamentals\node_modules\react-scripts\config\webpack.config.js:514:20)
    at Object.<anonymous> (C:\coding\react-fundamentals\node_modules\react-scripts\scripts\build.js:67:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\coding\\react-fundamentals\\node_modules\\postcss-loader\\package.json',
  requestPath: 'postcss-loader'
}
ERROR: "build" exited with 1.
```

**Comment by JCorrivo** [comment]
Deleting node_modules, package-lock.json and npm install anew has fixed the issue
