### ISSUE TITLE
terser-webpack-plugin throws error in project validation

### ISSUE THREAD

**Issue by ChandlerMBing** [kentcdodds/react-fundamentals#29]
Hey! I tried installing node_modules multiple times and each time it fails in `Project Validation`. Also tried installing the plugin as well as its dependency - terser - but to no avail. Anything I'm missing? 🙂

```
    ▶️  Starting: Project Validation
          Running validation checks to ensure dependencies were installed properly
          Running the following command: npm run validate -s
internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for '/Users/name/epic_react/react-fundamentals/node_modules/react-scripts/node_modules/terser'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/name/epic_react/react-fundamentals/node_modules/react-scripts/node_modules/terser-webpack-plugin/dist/minify.js:5:5)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
```

**Comment by JacobMGEvans** [comment]
Can I get more info on your system specs?
OS
Node Version

Also, the steps you take to reproduce, especially the CLI commands?

**Comment by ChandlerMBing** [comment]
@JacobMGEvans sure. 
OS: MacOS 10.15.2
Node: 13.5.0 - via nvm
npm: 6.14.2 - via nvm
git: 2.21.1

I tried a few of different ways:
1.
```
git clone https://github.com/kentcdodds/react-fundamentals.git
npm run setup --silent
```

2.
```
git clone https://github.com/kentcdodds/react-fundamentals.git
npm i
npm run setup --silent
```

3. ```
git clone https://github.com/kentcdodds/react-fundamentals.git
npm i -S terser-webpack-plugin terser
npm run setup --silent
```

I get the same output with or without `--silent` flag

**Comment by kentcdodds** [comment]
Can you try this with a stable version of Node? Odd versions of Node are experimental. Try upgrading to 14 or downgrading to 12.

**Comment by ChandlerMBing** [comment]
@kentcdodds that fixed it. Thank you! 🙂
