### ISSUE TITLE
ESLint server error

### ISSUE THREAD

**Issue by vchepeli** [kentcdodds/react-fundamentals#327]
When open project in vscode I see 
```
[Error - 20:31:46] ESLint stack trace:
[Error - 20:31:46] Error: Invalid Options:
- Unknown options: env, parserOptions, rules
- 'parserOptions' has been removed. Please use the 'overrideConfig.parserOptions' option instead.
- 'rules' has been removed. Please use the 'overrideConfig.rules' option instead.
    at processOptions (/Users/<redacted>/Documents/_CODE_/React/react-fundamentals/node_modules/eslint/lib/eslint/eslint.js:282:15)
    at new ESLint (/Users/<redacted>/Documents/_CODE_/React/react-fundamentals/node_modules/eslint/lib/eslint/eslint.js:429:34)
    at q (/Users/<redacted>/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:17975)
    at E (/Users/<redacted>/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:18312)
    at e.validate (/Users/<redacted>/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:23164)
    at /Users/<redacted>/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:210200
```

**Comment by kentcdodds** [comment]
Hi @vchepeli, I'm guessing there's a problem with your ESLint extension config because the lint script itself works in CI and it works for me in my VSCode instance.

**Comment by vchepeli** [comment]
> Hi @vchepeli, I'm guessing there's a problem with your ESLint extension config because the lint script itself works in CI and it works for me in my VSCode instance.

Hi @kentcdodds I use kcd settings for vscode, so not sure why server fails, seems extension error

**Comment by kentcdodds** [comment]
I hope it works itself out soon.
