### ISSUE TITLE
Project validation error while setting up the projecct

### ISSUE THREAD

**Issue by nehalv** [kentcdodds/react-fundamentals#48]
Hello, Am getting the following ES Lint error when I run the setup. Please advise.

 Am using node version v10.10.0
and 
npm --version 6.4.1
---------------
    ▶️  Starting: Project Validation
          Running validation checks to ensure dependencies were installed properly
          Running the following command: npm run validate -s

Oops! Something went wrong! :(

ESLint: 7.10.0

TypeError: createRequire is not a function
Referenced from: ~/code/epicreact/react-fundamentals/package.json
    at Object.resolve (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/shared/relative-module-resolver.js:40:20)
    at ConfigArrayFactory._loadExtendedShareableConfig (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/config-array-factory.js:872:39)
    at ConfigArrayFactory._loadExtends (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/config-array-factory.js:776:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/config-array-factory.js:715:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/config-array-factory.js:508:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:367:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:288:18)
    🚨  Failure: Project Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.

**Comment by nehalv** [comment]
I was able to resolve the issue by upgrading to node v12.16.1. Looks like ESlint 7+ requires node 10.12.0 or higher.

**Comment by kentcdodds** [comment]
Thanks for letting me know! I should update https://github.com/kentcdodds/react-fundamentals/blob/4593026200bed08c58ccbab8508b7be6263c4419/package.json#L11 (and the same in all the repos) so validation will fail with a more useful error message.

I'll reopen until I (or anyone else is welcome) get this done :)
