### ISSUE TITLE
Path names to built files are invalid in Windows

### ISSUE THREAD

**Issue by dustinsoftware** [kentcdodds/react-fundamentals#8]
Looks like an issue of `\` being interpreted as an escape character instead of a path separator.

![image](https://user-images.githubusercontent.com/942358/75893402-bea95200-5e00-11ea-968d-6db9526c2af3.png)

<details>

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\masters\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'setup'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.14.1
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle react-fundamentals@1.0.0~presetup: react-fundamentals@1.0.0
6 info lifecycle react-fundamentals@1.0.0~setup: react-fundamentals@1.0.0
7 verbose lifecycle react-fundamentals@1.0.0~setup: unsafe-perm in lifecycle true
8 verbose lifecycle react-fundamentals@1.0.0~setup: PATH: C:\Users\masters\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\code\kcd\react-fundamentals\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\adb;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\nodejs\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\masters\AppData\Local\Programs\AdoptOpenJDK\bin;C:\Users\masters\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\masters\AppData\Local\Programs\Python\Python37\;C:\Users\masters\AppData\Local\Programs\Python\Launcher\;C:\Users\masters\.dnx\bin;C:\Users\masters\AppData\Local\Microsoft\WindowsApps;C:\Users\masters\AppData\Local\Yarn\bin;C:\Users\masters\.dotnet\tools;C:\Users\masters\AppData\Local\Microsoft\WindowsApps;C:\Users\masters\AppData\Roaming\npm
9 verbose lifecycle react-fundamentals@1.0.0~setup: CWD: C:\code\kcd\react-fundamentals
10 silly lifecycle react-fundamentals@1.0.0~setup: Args: [ '/d /s /c', 'node ./scripts/setup' ]
11 silly lifecycle react-fundamentals@1.0.0~setup: Returned: code: 1  signal: null
12 info lifecycle react-fundamentals@1.0.0~setup: Failed to exec setup script
13 verbose stack Error: react-fundamentals@1.0.0 setup: `node ./scripts/setup`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\masters\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\masters\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid react-fundamentals@1.0.0
15 verbose cwd C:\code\kcd\react-fundamentals
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\masters\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
18 verbose node v12.14.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error react-fundamentals@1.0.0 setup: `node ./scripts/setup`
22 error Exit status 1
23 error Failed at the react-fundamentals@1.0.0 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

</details>

**Comment by kentcdodds** [comment]
Ah, interesting... Thank you for this. I'll get that fixed.

**Comment by kentcdodds** [comment]
I think I got this fixed. Do you mind trying again?

```
git clone https://github.com/kentcdodds/react-fundamentals.git
cd react-fundamentals
npm run setup --silent
```
