### ISSUE TITLE
Test suite failed to run

### ISSUE THREAD

**Issue by jeremypurser** [kentcdodds/react-fundamentals#86]
When I run `npm run setup --silent`, the last validation fails. I get the following output on the last step:
```
 Running validation checks to ensure dependencies were installed properly
          Running the following command: npm run validate -s
(node:13335) ExperimentalWarning: The fs.promises API is experimental
(node:13333) ExperimentalWarning: The fs.promises API is experimental
(node:13334) ExperimentalWarning: The fs.promises API is experimental

 FAIL  src/__tests__/06.extra-2.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)

 FAIL  src/__tests__/07.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)

 FAIL  src/__tests__/05.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)

 FAIL  src/__tests__/06.extra-3.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)

 FAIL  src/__tests__/06.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)

Test Suites: 5 failed, 5 total
Tests:       0 total
Snapshots:   0 total
Time:        4.271 s
Ran all test suites.
    🚨  Failure: Project Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.
```

**Comment by kentcdodds** [comment]
What version of node are you running?

**Comment by jeremypurser** [comment]
Hi @kentcdodds! I'm running `v10.14.1`. Sorry, I didn't realize I had opened this issue -- I had started the issue, but then deleted `node_modules`, ran `npm install`, and then the setup passed all of the validations after that.
